AuhofStation_SmallHouse_MapScripts::
	.byte 0


EventScript_OldMan_AuhofStation_SmallHouse::
	msgbox EventScript_OldMan_AuhofStation_SmallHouse_Text_0
	waitmessage
	closemessage
	return


EventScript_OldMan_AuhofStation_SmallHouse_Text_0:
	.string "Oh! Um.... Hey Kid I am just growing some\n"
	.string "'herbs' here..... so I can ... cook with\l"
	.string "them.... Yeah that's it. Oh you are\l"
	.string "looking for my son? He went to Route 3,\l"
	.string "west of here, to smash some rocks!$"
